In [1]:
import pandas as pd
import numpy as np
import os,sys
from Utils.utils import *

In [23]:
#1 model the decision
# n_patients with characteristics
np.random.seed(2)
fake_dta = np.vstack([np.arange(100),
                      np.random.randint(0,100,size=100),
                      np.random.randint(0,7,size=100),
                     ]).T
df = pd.DataFrame(fake_dta,columns=['ID','Core_vol','mRS_EVT'])

Tx_EVT = 1.3 
Tx_EVT_corevol = 1
# condition (<70 ml core) True/False
df

    ID  Core_vol  mRS_EVT
0    0        40        5
1    1        15        0
2    2        72        0
3    3        22        6
4    4        43        2
5    5        82        5
6    6        75        3
7    7         7        1
8    8        34        6
9    9        49        5
10  10        95        2
11  11        75        3
12  12        85        4
13  13        47        3
14  14        63        6
15  15        31        3
16  16        90        1
17  17        20        4
18  18        37        2
19  19        39        3
20  20        67        0
21  21         4        6
22  22        42        0
23  23        51        2
24  24        38        5
25  25        33        4
26  26        58        4
27  27        67        3
28  28        69        6
29  29        88        2
..  ..       ...      ...
70  70        70        3
71  71        86        0
72  72        70        1
73  73        19        4
74  74        56        2
75  75        82        1
76  76         1        5
77  77        68        1
78  78        40        2
79  79        81        0
80  80        61        2
81  81        70        0
82  82        97        4
83  83        18        6
84  84        84        3
85  85        90        1
86  86        87        5
87  87        22        0
88  88        43        5
89  89        52        1
90  90        74        5
91  91        72        4
92  92        90        2
93  93        99        0
94  94        91        3
95  95        96        3
96  96        16        2
97  97        55        4
98  98        21        0
99  99        43        6

[100 rows x 3 columns]

In [3]:
# initial distribution in numbers

array([ 9, 45, 18, 46,  7, 93, 27, 10, 64, 69, 67, 38, 68, 45,  8, 84, 17,
       15, 23,  3, 45, 29, 78, 55, 45, 25, 45, 41, 23, 41, 15, 23, 88, 54,
       43, 22, 90, 41, 24, 11, 28, 57, 76, 62, 81, 93, 25, 81,  9, 41, 31,
       31, 29, 38, 49, 21, 63, 73, 58, 21, 91, 33,  6,  3, 17, 86, 17, 38,
       64, 81, 72, 49, 22, 79, 57,  7, 76, 78, 32, 22, 11, 62, 20, 98, 46,
       23, 26, 62, 82, 37, 32, 82, 82, 88, 81, 46, 87, 79, 81, 69])